# mTLS-enabled KV Store deployment for Kubernetes
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  clusterIP: 10.96.88.88
  ports:
  - name: frontend
    port: 80
    targetPort: 8080
  selector:
    app: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
      - image: appnetorg/kvstore-arpc-tcp:latest
        name: frontend-kvstore-arpc-tcp
        command: ["/app/frontend"]
        args:
        - "-mtls"
        - "-tls-ca-file=/app/certs/ca-cert.pem"
        - "-tls-client-cert-file=/app/certs/client-cert.pem"
        - "-tls-client-key-file=/app/certs/client-key.pem"
        - "-server=kvstore.default.svc.cluster.local:11000"
        env:
        - name: LOG_LEVEL
          value: info
        volumeMounts:
        - name: tls-certs
          mountPath: /app/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kvstore-tls-certs
  selector:
    matchLabels:
      app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: kvstore
  labels:
    app: kvstore
spec:
  clusterIP: None
  ports:
  - name: kvstore
    port: 11000
    protocol: TCP  
    targetPort: 11000
  selector:
    app: kvstore
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvstore
spec:
  replicas: 1
  template:
    metadata:
      name: kvstore
      labels:
        app: kvstore
    spec:
      containers:
      - image: appnetorg/kvstore-arpc-tcp:latest
        name: kvstore-kvstore-arpc-tcp
        command: ["/app/kvstore"]
        args:
        - "-mtls"
        - "-tls-cert-file=/app/certs/server-cert.pem"
        - "-tls-key-file=/app/certs/server-key.pem"
        - "-tls-ca-file=/app/certs/ca-cert.pem"
        - "-listen=:11000"
        env:
        - name: LOG_LEVEL
          value: info
        volumeMounts:
        - name: tls-certs
          mountPath: /app/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: kvstore-tls-certs
  selector:
    matchLabels:
      app: kvstore

